[tableau]
token_name = "bharat-refinery"
personal_access_token = "dD5aRcYnSBmRnGdPiELXRQ==:2FGw7vWhf23mjzbrZ8aYkuCWggaC0A0f"
server_url = "https://prod-apnortheast-a.online.tableau.com/"
site_id = "bharatrefinery"  # in your site's URL behind the server_url